<?php

    return [
        'labels' => [
            'GENtitle' => 'Title',
            'GENname' => 'Name',
            'GENsurname' => 'Surname',
            'GENSex' => 'Sex',
            'GENline1' => 'Line 1',
            'GENline2' => 'Line 2',
            'GENlocality' => 'Locality',
            'GENposcode' => 'Postcode',
            'GENcountry' => 'Country',
            'GENnationality' => 'Nationality',
            'GENdob' => 'Date of birth',
            'GENpob' => 'Place of birth',
            'GENmaritalstatus' => 'Marital Status',
            'GENdoctype' => 'Identification document type',
            'GENdocnumber' => 'Identification document number',
            'GENdoccountry' => 'Identification document dountry of issue',
            'GENdocexpiry' => 'Identification document expiry date',
            'GENemail' => 'E-mail Address',
            'GENmobile' => 'Mobile Number',
            'GENpweproduct' => 'PWE Product',
            'GENindustry' => 'Industry',
            'GENsow' => 'Source of wealth',
            'GENsowother' => 'Source of wealth - Other income',
            'GENsowverified' => 'Source of wealth verified?',
            'GENestannualincoming' => 'What is the estimated annual incoming funds that will be channelled through the account?',
            'GENhnwi' => 'Is the customer a high net worth individual?',
            'GENiipapplicant' => 'Is the customer a IIP applicant?',
            'GENpep' => 'PEP',
            'GENtin' => 'TIN',
            'GENcountrytax' => 'Country of Tax Residence',
            'GENuscitizenship' => 'US Citizenship',
            'GENfacetoface' => 'Face to Face',
            'GENreluctant' => 'Did the customer show signs of reluctancy to comply with our CDD requirements?',
            'GENsanctioned' => 'Sanctioned',
            'GENadversemedia' => 'Adverse Media',
            'GENpeepscreening' => 'Peep screening',
            'GENotherfindings' => 'Other Relevant Findings'
        ],
        'countries' => [
            'GENcountryoflicense',
            'GENcountrytax',
            'GENregcountry',
            'GENCounInPay',
            'GenSaleVol',
            'GenCounOutPay',
            'GENInPart',
            'GENopcountry',
            'GENcountry',
            'GENdoccountry',
            'GENcountrytax',
            'GENcountryincorp',
            'GENjurisdealing',
            'GENnationality',
            'GENpob'
        ],
        'GENDocComplex' => [
            'GENdoctype',
            'GENdocnumber',
            'GENdoccountry',
            'GENdocexpiry',
            'GENdocissdate'
        ],
        // Natural Persons
        '1' => [
            'fields' => [
                'GENtitle' => 'title',
                'GENname' => 'name',
                'GENsurname' => 'surname',
                'GENSex' => 'sex',
                'GENline1' => 'registered_address.line_1',
                'GENline2' => 'registered_address.line_2',
                'GENlocality' => 'address.locality',
                'GENposcode' => 'registered_address.postal_code',
                'GENcountry' => 'registered_address.country',
                'GENnationality' => 'nationality',
                'GENdob' => 'date_of_birth',
                'GENpob' => 'place_of_birth',
                'GENemail' => 'email_address',
                'GENmobile' => 'mobile',
                'GENsow' => 'additional_info.source_of_wealth',
                'GENsowother' => 'additional_info.other_source_of_wealth_details',
                'GENpep' => 'additional_info.pep',
                'GENtin' => 'additional_info.tin',
                'GENcountrytax' => 'additional_info.country_tax',
                'GENuscitizenship' => 'additional_info.us_citizenship'
            ],
        ],
        // Company
        '2' => [
            'fields' => [
                'GENname' => 'name',
                'GENregnumber' => 'tax_information.registration_number',
                'GENdateincorp' => 'foundation_date',
                'GENcountryincorp' => 'business_details.country_of_license',
                'GENvatnumber' => 'vat_number',
                'GENphonenumber' => 'telephone',
                'GENemail' => 'email',
                'GENWebsite' => 'website',
                'GENAddWebSites' => 'additional_website',
                'GENregline1' => 'registered_address.line_1',
                'GENregline2' => 'registered_address.line_2',
                'GENregposcode' => 'registered_address.postal_code',
                'GENregcountry' => 'registered_address.country',
                'GENopline1' => 'operational_address.line_1',
                'GENopline2' => 'operational_address.line_2',
                'GENopposcode' => 'operational_address.postal_code',
                'GENopcountry' => 'operational_address.country',
                'email' => 'contact_details.email',
                'GENmobile' => 'contact_details.mobile_no',
                'GENposition' => 'contact_details.position_held',
                'GENpweproduct' => 'business_details.finxp_products',
                'GENindustry' => 'business_details.industry_key',
                'GENBusinessActivity' => 'business_details.business_purpose',
                'GENNoEmp' => 'business_details.number_employees',
                'GENsharecapital' => 'business_details.share_capital',
                'GENnoofshrhld' => 'business_details.number_shareholder',
                'GENNoDirectors' => 'business_details.number_directors',
                'GENPreYTO' => 'business_details.previous_year_turnover',
                'GENlicenserepjuris' => 'business_details.license_rep_juris',
                'GENcountryoflicense' => 'business_details.country_of_license',
                'GENjurisdealing' => 'business_details.country_juris_dealings',
                'GENNoYearsBusiness' => 'business_details.business_year_count',
                'GenIBANYN' => 'iban4u_processing',
                'GENPurposeOfAcc' => 'iban4u_payment_account.purpose_of_account_opening',
                'GENInPart' => 'iban4u_payment_account.partners_incoming_transactions',
                'SPEcountryorigin' => 'iban4u_payment_account.country_origin',
                'GENCounInPay' => 'iban4u_payment_account.partners_incoming_transactions',
                'SPEcountryremittance' => 'iban4u_payment_account.country_remittance',
                'GenCounOutPay' => 'iban4u_payment_account.partners_outgoing_transactions',
                'GENEstimNoMonthTrns' => 'iban4u_payment_account.estimated_monthly_transactions',
                'GENEstAveofTrans' => 'iban4u_payment_account.average_amount_transaction_euro',
                'GENcountry' => 'registered_address.country',
                'GenCCCBVol12M' => 'credit_card_processing.cb_volumes_twelve_months',
                'GenCCVol12M' => 'credit_card_processing.cc_volumes_twelve_months',
                'GenCCRefVol12' => 'credit_card_processing.refund_volumes_twelve_months',
                'GenDDCurProcs' => 'sepa_dd_direct_debit.currently_processing_sepa_dd',
                'GenDDPricing' => 'sepa_dd_direct_debit.sepa_dd_volume_per_month',
                'GenDDVol' => 'sepa_dd_direct_debit.sepa_dd_volume_per_month',
                'GENcompany' => 'name',
                'GENPrivacy' => 'business_details.privacy_accepted',
                'GENTerms' => 'business_details.terms_and_conditions',
                'GENMID' => 'business_details.mid',
                'GENCredID' => 'business_details.creditor_identifier',
                'GenREFBP' => 'external_identifier',
                'GenSetIBAN' => 'IBAN'
            ],
        ],
        // Shareholder Corporate
        '8' => [
            'fields' => [
                'GENname' => 'tax_information.name',
                'GENregnumber' => 'tax_information.registration_number',
                'GENregline1' => 'address.line_1',
                'GENregline2' => 'address.line_2',
                'GENregposcode' => 'address.postal_code',
                'GENregcountry' => 'address.country',
                'GENlicenserepjuris' => 'business_details.license_rep_juris',
                'GENsharholders' => 'business_details.number_shareholder',
                'GENsharecapital' => 'business_details.share_capital'
            ]
        ],
        // Shareholder Natural Person
        '9' => [
            'fields' => [
                'GENtitle' => 'title',
                'GENname' => 'name',
                'GENsurname' => 'surname',
                'GENemail' => 'email_address',
                'GENSex' => 'sex',
                'GENline1' => 'registered_address.line_1',
                'GENline2' => 'registered_address.line_2',
                'GENlocality' => 'address.locality',
                'GENposcode' => 'registered_address.postal_code',
                'GENcountry' => 'registered_address.country',
                'GENnationality' => 'nationality',
                'GENdob' => 'date_of_birth',
                'GENpob' => 'place_of_birth',
                'GENmobile' => 'mobile',
                'GENOccupation' => 'additional_info.occupation',
                'GENEmployment' => 'additional_info.employment',
                'GENposition' => 'additional_info.position',
                'GENSoIncome' => 'additional_info.source_of_income',
                'GENsow' => 'additional_info.source_of_wealth',
                'GENsowother' => 'additional_info.other_source_of_wealth_details',
                'GENsowverified' => 'null',
                'GENpep' => 'additional_info.pep',
                'GENuscitizenship' => 'additional_info.us_citizenship',
                'GENcountrytax' => 'additional_info.country_tax',
                'GENcountryincorp' => 'additional_info.country_tax'
            ]
        ],
        // UBO
        '10' => [
            'fields' => [
                'GENtitle' => 'title',
                'GENname' => 'name',
                'GENsurname' => 'surname',
                'GENSex' => 'sex',
                'GENline1' => 'registered_address.line_1',
                'GENline2' => 'registered_address.line_2',
                'GENlocality' => 'address.locality',
                'GENposcode' => 'registered_address.postal_code',
                'GENcountry' => 'registered_address.country',
                'GENnationality' => 'nationality',
                'GENdob' => 'date_of_birth',
                'GENpob' => 'place_of_birth',
                'GENemail' => 'email_address',
                'GENmobile' => 'mobile',
                'GENposition' =>  'additional_info.position',
                'GENsow' =>  'additional_info.source_of_wealth',
                'GENsowother' =>  'additional_info.other_source_of_wealth_details',
                'GENpep' =>  'additional_info.pep',
                'GENtin' =>  'additional_info.tin',
                'GENcountrytax' =>  'additional_info.country_tax',
                'GENuscitizenship' =>  'additional_info.us_citizenship',
                'GENpepscreening' =>  'additional_info.pep'
            ]
        ],
        // Director Corporate
        '11' => [
            'fields' => [
                'GENname' => 'name',
                'GENregnumber' => 'registration_number',
                'GENdateincorp' => 'date_of_incorporation',
                'GENcountryincorp' => 'country_of_incorporation',
                'GENregline1' => 'address.line_1',
                'GENregline2' =>  'address.line_2',
                'GENreglocality' =>  'address.locality',
                'GENregposcode' =>  'address.postal_code',
                'GENregcountry' =>  'address.country'
            ]
        ],
        // Director Natural Person
        '12' => [
            'fields' => [
                'GENtitle' => 'title',
                'GENname' => 'name',
                'GENsurname' => 'surname',
                'GENSex' => 'sex',
                'GENline1' => 'address.line_1',
                'GENline2' => 'address.line_2',
                'GENlocality' => 'address.locality',
                'GENposcode' => 'registered_address.postal_code',
                'GENcountry' => 'registered_address.country',
                'GENnationality' => 'nationality',
                'GENdob' => 'date_of_birth',
                'GENpob' => 'place_of_birth',
                'GENemail' => 'email_address',
                'GENmobile' => 'mobile',
                'GENpep' => 'additional_info.pep',
                'GENtin' => 'additional_info.tin',
                'GENcountrytax' => 'additional_info.country_tax',
                'GENuscitizenship' => 'additional_info.us_citizenship'
            ]
        ],
        // Company Secretary
        '13' => [
            'fields' => [
                'GENtitle' => 'title',
                'GENname' => 'name',
                'GENsurname' => 'surname',
                'GENSex' => 'sex',
                'GENline1' => 'registered_address.line_1',
                'GENline2' => 'registered_address.line_2',
                'GENlocality' => 'address.locality',
                'GENposcode' => 'registered_address.postal_code',
                'GENcountry' => 'registered_address.country',
                'GENnationality' => 'nationality',
                'GENdob' => 'date_of_birth',
                'GENpob' => 'place_of_birth',
                'GENemail' => 'email_address',
                'GENmobile' => 'mobile',
                'GENposition' => 'additional_info.position',
                'GENpep' => 'additional_info.pep',
                'GENtin' => 'additional_info.tin',
                'GENcountrytax' => 'additional_info.country_tax',
                'GENuscitizenship' => 'additional_info.us_citizenship'
            ]
        ],
        // Administrator/Authorised Signatory
        '14' => [
            'fields' => [
                'GENtitle' => 'title',
                'GENname' => 'name',
                'GENsurname' => 'surname',
                'GENSex' => 'sex',
                'GENline1' => 'registered_address.line_1',
                'GENline2' => 'registered_address.line_2',
                'GENreglocality' => 'address.locality',
                'GENlocality' => 'address.locality',
                'GENposcode' => 'registered_address.postal_code',
                'GENcountry' => 'registered_address.country',
                'GENnationality' => 'nationality',
                'GENdob' => 'date_of_birth',
                'GENpob' => 'place_of_birth',
                'GENemail' => 'email_address',
                'GENmobile' => 'mobile',
                'GENposition' => 'additional_info.position',
                'GENpep' => 'additional_info.pep',
                'GENuscitizenship' => 'additional_info.us_citizenship',
                'GENtin' => 'additional_info.tin',
                'GENcountrytax' => 'additional_info.country_tax'
            ]
        ]
    ];
