<?php
    return [
        'countries' => [
            'GENcountryoflicense',
            'GENcountrytax',
            'GENregcountry',
            'GENCounInPay',
            'GenSaleVol',
            'GenCounOutPay',
            'GENInPart',
            'GENopcountry',
            'GENcountry',
            'GENdoccountry',
            'GENcountrytax',
            'GENcountryincorp',
            'GENjurisdealing',
            'GENnationality',
            'GENpob'
        ],
        'GENDocComplex' => [
            'GENdoctype',
            'GENdocnumber',
            'GENdoccountry',
            'GENdocexpiry',
            'GENdocissdate'
        ],
         // Natural Persons
        '1' => [
            'fields' => [
                'GENtitle' => null,
                'GENname' => 'first_name',
                'GENsurname' => 'surname',
                'GENSex' => null,
                'GENline1' => 'residential_address.street_number',
                'GENline2' => 'residential_address.street_name',
                'GENlocality' => 'residential_address.city',
                'GENposcode' => 'residential_address.postal_code',
                'GENcountry' => 'residential_address.country',
                'GENdob' => 'date_of_birth',
                'GENnationality' => 'nationality',
                'GENpob' => 'place_of_birth',
                'GENemail' => 'email_address',
                'GENSpecificEmail' => 'email_address',
                'GENmobile' => 'phone_code_number',
                'GENsow' => null,
                'GENsowother' => null,
                'GENpep' => 'identity_information.politically_exposed_person',
                'GENtin' => null,
                'GENcountrytax' => null,
                'GENuscitizenship' => 'identity_information.us_citizenship',
                'GENdoctype' => 'identity_information.id_type',
                'GENdocnumber' => 'identity_information.id_number',
                'GENdoccountry' => 'identity_information.country_of_issue',
                'GENdocexpiry' => 'identity_information.document_expired_date',
                'GENdocissdate' => 'identity_information.document_date_issued',
                'GENhnwi' => 'identity_information.high_net_worth'
            ],
        ],
        // Company
        '2' => [
            'fields' => [
                'GENname' => 'company_details.name',
                'GENDDProdName' => 'products',
                'GenDDProd' => 'products',
                'GENregnumber' => 'company_details.registration_number',
                'GENtin' => 'company_details.tax_identification_number',
                'GENdateincorp' => 'company_details.foundation_date',
                'GENcountryincorp' => 'company_details.tax_country',
                'GENvatnumber' => 'company_details.vat_number',
                'GENphonenumber' => 'company_details.telephone',
                'GENemail' => 'company_details.email',
                'GENWebsite' => 'company_details.website',
                'GENAddWebSites' => 'company_details.additional_website',
                'GENcompanytype' => 'company_details.registration_type',
                'GENregline1' => 'registered_address.registered_street_number',
                'GENregline2' => 'registered_address.registered_street_name',
                'GENregposcode' => 'registered_address.registered_postal_code',
                'GENreglocality' => 'registered_address.registered_city',
                'GENregcountry' => 'registered_address.registered_country',
                'GENopline1' => 'operational_address.operational_street_number',
                'GENopline2' => 'operational_address.operational_street_name',
                'GENoplocality' => 'operational_address.operational_city',
                'GENopposcode' => 'operational_address.operational_postal_code',
                'GENopcountry' => 'operational_address.operational_country',
                'GENsameasreg' => 'is_same_address',
                'GENsurname' => 'company_details.contact_person_name',
                'email' => 'company_details.contact_person_email',
                'GENjurisdealing' => 'company_details.tax_country',
                'GENmobile' => 'contact_details.mobile_no',
                'GENposition' => 'contact_details.position_held',
                'GENpweproduct' => 'products',
                'GENindustry' => 'company_details.industry_type',
                'GENBusinessActivity' => 'company_details.business_activity_description',
                'GENNoEmp' => 'company_details.number_employees',
                'GENsharecapital' => 'company_details.share_capital',
                'GENnoofshrhld' => 'company_details.number_shareholder',
                'GENNoDirectors' => 'company_details.number_directors',
                'GENNoYearsBusiness' => 'company_details.number_of_years',
                'GENPreYTO' => 'company_details.previous_year_turnover',
                'GENlicenserepjuris' => 'company_details.is_company_licensed',
                'GENcountryoflicense' => 'company_details.license_rep_juris',
                'GenIBANYN' => 'iban4u_processing',
                'GenTradeName' => 'company_details.trading_name',
                'GenTINJurisdiction' =>  'company_details.tin_jurisdiction',
                'GENIsGroup' => 'company_details.is_group_corporate',
                'GenParentHold' => 'company_details.parent_holding_company_other',
                'GenSharesFidu' => 'company_details.has_fiduciary_capacity',
                'GenBearer' => 'company_details.has_constituting_documents',

                'GENPurposeOfAcc' => 'iban4u_payment_account.purpose_of_account_opening',
                'GENestannualincoming' => 'iban4u_payment_account.annual_turnover',
                'GENInPart' => 'iban4u_payment_account.activity.incoming_payments',
                'GenOutPart' => 'iban4u_payment_account.activity.outgoing_payments',
                'SPEcountryorigin' => 'iban4u_payment_account.country_origin',
                'GENCounInPay' => 'iban4u_payment_account.deposit.countries',
                'SPEcountryremittance' => 'iban4u_payment_account.country_remittance',
                'GenCounOutPay' => 'iban4u_payment_account.withdrawal.countries',
                'GENEstimNoMonthTrns' => 'iban4u_payment_account.estimated_monthly_transactions',
                'GENEstAveofTrans' => 'iban4u_payment_account.average_amount_transaction_euro',
                'GENcountry' => 'registered_address.registered_country',
                'GenOtherBanks' => 'iban4u_payment_account.activity.held_accounts',
                'GenOtherBanksDetail' => 'iban4u_payment_account.activity.held_accounts_description',
                'GenRefusedBank' => 'iban4u_payment_account.activity.refused_banking_relationship',
                'GenRefusedReason' => 'iban4u_payment_account.activity.refused_banking_relationship_description',
                'GenBankTerminated' => 'iban4u_payment_account.activity.terminated_banking_relationship',
                'GenBankTermReason' => 'iban4u_payment_account.activity.terminated_banking_relationship_description',

                'GenCCYN' => 'credit_card_processing',
                'GenTradingURLs' => 'credit_card_processing.trading_urls',
                'GenRecurBill' => 'credit_card_processing.offer_recurring_billing',
                'GenRecurDetails' => ['credit_card_processing.frequency_offer_billing','credit_card_processing.if_other_offer_billing'],
                'GenRefunds' => 'credit_card_processing.offer_refunds',
                'GenRefundDetails' => ['credit_card_processing.frequency_offer_refunds','credit_card_processing.if_other_offer_refunds'],
                'GenSaleVol' => 'credit_card_processing.sales_volumes_twelve_months',
                'GenCurrecy' => 'credit_card_processing.processing_account_primary_currency',
                'GenTickAmou' => 'credit_card_processing.average_ticket_amount',
                'GenHighTicAmount' => 'credit_card_processing.highest_ticket_amount',
                'GenAPM' => 'credit_card_processing.alternative_payment_methods',
                'GenAPMUsed' => 'credit_card_processing.payment_method_currently_offered',
                'GenMCC' => 'credit_card_processing.current_mcc',
                'GenCurrDescp' => 'credit_card_processing.current_descriptor',
                'GenCCCBVol12M' => 'credit_card_processing.cb_volumes_twelve_months',
                'GenCCVol12M' => 'credit_card_processing.sales_volumes_twelve_months',
                'GenCCRefVol12' => 'credit_card_processing.refund_twelve_months',

                'GenCCCurPross' => 'sepa_direct_debit.processing_sepa_dd', //only programid: 7 exist
                'SEPADD_YN' => 'sepa_direct_debit.processing_sepa_dd',
                'GenDDProd' => 'sepa_direct_debit.sepa_dd_products.name',
                'GenDDCurProcs' => 'sepa_direct_debit.currently_processing_sepa_dd',
                'GenDDPricing' => 'sepa_direct_debit.sepa_dd_products.value', //lowest
                'GenDDPricingHIGH' => 'sepa_direct_debit.sepa_dd_products.value', //highest
                'GenDDVol' => 'sepa_direct_debit.expected_global_mon_vol',

                'GENcompany' => 'name',
                'GENPrivacy' => 'privacy_accepted',
                'GENTerms' => 'terms_and_conditions',
                'GENMID' => 'mid',
                'GENCredID' => 'creditor_identifier'
            ],
        ],
        // Shareholder Natural Person
        '9' => [
            'fields' => [
                'GENtitle' =>  null,
                'GENname' => 'first_name',
                'GENsurname' => 'surname',
                'GENemail' => 'email_address',
                'GENSpecificEmail' => 'email_address',
                'GENSex' =>  null,
                'GENline1' => 'residential_address.street_number',
                'GENline2' => 'residential_address.street_name',
                'GENlocality' => 'residential_address.city',
                'GENposcode' => 'residential_address.postal_code',
                'GENcountry' => 'residential_address.country',
                'GENnationality' => 'nationality',
                'GENpob' => 'place_of_birth',
                'GENdob' => 'date_of_birth',
                'GENmobile' => null,
                'GENOccupation' => null,
                'GENEmployment' => null,
                'GENposition' => 'residential_address.roles.roles_in_company',
                'GENSoIncome' => null,
                'GENsow' => null,
                'GENsowother' => null,
                'GENsowverified' => null,
                'GENpep' => 'identity_information.politically_exposed_person',
                'GENuscitizenship' => 'identity_information.us_citizenship',
                'GENcountrytax' => null,
                'GENcountryincorp' => null,
                'GENdoctype' => 'identity_information.id_type',
                'GENdocnumber' => 'identity_information.id_number',
                'GENdoccountry' => 'identity_information.country_of_issue',
                'GENdocexpiry' => 'identity_information.document_expired_date',
                'GENdocissdate' => 'identity_information.document_date_issued'
            ]
        ],
        // UBO
        '10' => [
            'fields' => [
                'GENtitle' => null,
                'GENname' => 'first_name',
                'GENsurname' => 'surname',
                'GENSex' => null,
                'GENline1' => 'residential_address.street_number',
                'GENline2' => 'residential_address.street_name',
                'GENlocality' => 'residential_address.city',
                'GENposcode' => 'residential_address.postal_code',
                'GENcountry' => 'residential_address.country',
                'GENdob' => 'date_of_birth',
                'GENnationality' => 'nationality',
                'GENpob' => 'place_of_birth',
                'GENemail' => 'email_address',
                'GENSpecificEmail' => 'email_address',
                'GENmobile' => 'phone_code_number',
                'GENposition' =>  'roles.roles_in_company',
                'GENsow' => null,
                'GENsowother' => null,
                'GENpep' => 'identity_information.politically_exposed_person',
                'GENtin' =>  null,
                'GENcountrytax' => null,
                'GENuscitizenship' => 'identity_information.us_citizenship',
                'GENpepscreening' => null,
                'GENdoctype' => 'identity_information.id_type',
                'GENdocnumber' => 'identity_information.id_number',
                'GENdoccountry' => 'identity_information.country_of_issue',
                'GENdocexpiry' => 'identity_information.document_expired_date',
                'GENdocissdate' => 'identity_information.document_date_issued',
                'GENpercshareholding' => 'roles.percent_ownership',
                'GENhnwi' =>'identity_information.high_net_worth'
            ]
        ],
        // Director Corporate
        '11' => [
            'fields' => [
                'GENname' => 'name',
                'GENregnumber' => 'registration_number',
                'GENdateincorp' => 'date_of_incorporation',
                'GENcountryincorp' => 'country_of_incorporation',
                'GENregline1' => 'address.line_1',
                'GENregline2' =>  'address.line_2',
                'GENreglocality' =>  'address.locality',
                'GENregposcode' =>  'address.postal_code',
                'GENregcountry' =>  'address.country'
            ]
        ],
        // Director Natural Person
        '12' => [
            'fields' => [
                'GENtitle' => null,
                'GENname' => 'first_name',
                'GENsurname' => 'surname',
                'GENSex' => null,
                'GENline1' => 'residential_address.street_number',
                'GENline2' => 'residential_address.street_name',
                'GENlocality' => 'residential_address.city',
                'GENposcode' => 'residential_address.postal_code',
                'GENcountry' => 'residential_address.country',
                'GENnationality' => 'nationality',
                'GENpob' => 'place_of_birth',
                'GENdob' => 'date_of_birth',
                'GENemail' => 'email_address',
                'GENSpecificEmail' => 'email_address',
                'GENmobile' => 'phone_code_number',
                'GENpep' => 'identity_information.politically_exposed_person',
                'GENtin' => null,
                'GENcountrytax' => null,
                'GENuscitizenship' => 'identity_information.us_citizenship',
                'GENdoctype' => 'identity_information.id_type',
                'GENdocnumber' => 'identity_information.id_number',
                'GENdoccountry' => 'identity_information.country_of_issue',
                'GENdocexpiry' => 'identity_information.document_expired_date',
                'GENdocissdate' => 'identity_information.document_date_issued'
            ]
        ],
        // Company Secretary
        '13' => [
            'fields' => [
                'GENtitle' => null,
                'GENname' => 'first_name',
                'GENsurname' => 'surname',
                'GENSex' => null,
                'GENline1' => 'residential_address.street_number',
                'GENline2' => 'residential_address.street_name',
                'GENlocality' => 'residential_address.city',
                'GENposcode' => 'residential_address.postal_code',
                'GENcountry' => 'residential_address.country',
                'GENdob' => 'date_of_birth',
                'GENnationality' => 'nationality',
                'GENpob' => 'place_of_birth',
                'GENemail' => 'email_address',
                'GENSpecificEmail' => 'email_address',
                'GENmobile' => 'phone_code_number',
                'GENposition' => 'roles.roles_in_company',
                'GENpep' => 'identity_information.politically_exposed_person',
                'GENtin' => null,
                'GENcountrytax' => null,
                'GENuscitizenship' => 'identity_information.us_citizenship',
                'GENdoctype' => 'identity_information.id_type',
                'GENdocnumber' => 'identity_information.id_number',
                'GENdoccountry' => 'identity_information.country_of_issue',
                'GENdocexpiry' => 'identity_information.document_expired_date',
                'GENdocissdate' => 'identity_information.document_date_issued'
            ]
        ],
        // Administrator/Authorised Signatory
        '14' => [
            'fields' => [
                'GENtitle' => null,
                'GENname' => 'first_name',
                'GENsurname' => 'surname',
                'GENSex' => null,
                'GENline1' => 'residential_address.street_number',
                'GENline2' => 'residential_address.street_name',
                'GENlocality' => 'residential_address.city',
                'GENposcode' => 'residential_address.postal_code',
                'GENcountry' => 'residential_address.country',
                'GENnationality' => 'nationality',
                'GENpob' => 'place_of_birth',
                'GENdob' => 'date_of_birth',
                'GENemail' => 'email_address',
                'GENSpecificEmail' => 'email_address',
                'GENmobile' => 'phone_code_number',
                'GENposition' => 'roles.roles_in_company',
                'GENpep' => 'identity_information.politically_exposed_person',
                'GENuscitizenship' => 'identity_information.us_citizenship',
                'GENtin' => null,
                'GENcountrytax' => null,
                'GENdoctype' => 'identity_information.id_type',
                'GENdocnumber' => 'identity_information.id_number',
                'GENdoccountry' => 'identity_information.country_of_issue',
                'GENdocexpiry' => 'identity_information.document_expired_date',
                'GENdocissdate' => 'identity_information.document_date_issued',
                'GENSignRightsSpecific' => 'roles'
            ]
        ]
    ];
